baseURL = "https://test-course-site.netlify.app/"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "Scientific Rmd Blogging"
enableEmoji = true
pygmentsUseClasses=true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "index\\.html", '\.knit\.md$', '\.utf8\.md$']

[module]
  [[module.imports]]
    path = "github.com/matcornic/hugo-theme-learn"
  [[module.imports]]
    path = "github.com/dzello/reveal-hugo"
    
[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true


[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Scientific Rmd Blogging"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/maelle/test-course-site"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[params]
  editURL = "https://github.com/maelle/rmd-blogging-course/edit/main/content/"
  description = "Test of a course website"
  author = "MaÃ«lle Salmon"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params.reveal_hugo]
theme = "white"
load_default_plugins = false
plugins = [
  "reveal-js/plugin/zoom-js/zoom.js",
  "reveal-js/plugin/notes/notes.js",
]
